version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.2.2
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-connect:
    build: ./kafka-connect
    depends_on:
      - zookeeper
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: mongo-group
      CONNECT_CONFIG_STORAGE_TOPIC: mongo-group-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: mongo-group-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: mongo-group-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components/
      
  kafka-connect-init:
    build: ./kafka-connect/init
    depends_on:
      - zookeeper
      - kafka
      - kafka-connect
    environment:
        SLEEP_TIME: 30
    entrypoint: /curl.sh
    volumes:
      - ./kafka-connect/init/curl.sh:/curl.sh
      - ./kafka-connect/init/source.json:/source.json
      - ./kafka-connect/init/target.json:/target.json
    restart: no

  source:
    image: mongo:6.0.5
    depends_on:
      - zookeeper
      - kafka
      - kafka-connect
    environment:
        SLEEP_TIME: 10
    ports:
      - 27017:27017
    command: --replSet rs0 --oplogSize 128
    volumes:
      - ./source/db:/data/db
      - ./source/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always

  target:
    image: mongo:6.0.5
    depends_on:
      - zookeeper
      - kafka
      - kafka-connect
    ports:
      - 27018:27017
    volumes:
      - ./target/db:/data/db
      - ./target/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always